# fly.toml app configuration file generated for full-stack-open-pokedex-aged-sound-109 on 2025-05-27T10:59:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file
#

app = 'full-stack-open-pokedex-aged-sound-109'
primary_region = 'arn'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  interval = "10s"
  timeout = "5s"
  grace_period = "15s"
  method = "get"
  path = "/health"
  protocol = "http"
  restart_limit = 0

[deploy]
  strategy = "canary"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
