name: Notify if No Reviewer Assigned

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  check-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has reviewers
        id: check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requestedReviewers = context.payload.pull_request.requested_reviewers || [];
            
            const humanReviewers = requestedReviewers.filter(reviewer => 
              reviewer.type === 'User' &&
              !/bot|copilot|github-actions/i.test(reviewer.login)
            );
            
            const hasHumanReviewers = humanReviewers.length > 0;
            
            console.log(`PR has human reviewers: ${hasHumanReviewers}`);
            console.log(`All requested reviewers: ${requestedReviewers.map(r => `${r.login} (${r.type})`).join(', ')}`);
            console.log(`Human reviewers only: ${humanReviewers.map(r => r.login).join(', ') || 'None'}`);
            
            core.setOutput('has_reviewers', hasHumanReviewers);

      - name: Find existing comment
        if: steps.check.outputs.has_reviewers == 'false'
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Please request a reviewer for this PR'

      - name: Create or update comment
        if: steps.check.outputs.has_reviewers == 'false'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @kreuz123 Please request a reviewer for this PR.
          edit-mode: replace
