name: Sync urgent label from issue to PR

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  sync-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check related issues and add 'urgent' to PR if needed
        uses: actions/github-script@v7
        with:
          script: |
            // 1) 從 PR body 擷取第一個 #<number>
            const body = context.payload.pull_request?.body || '';
            const m = body.match(/#(\d+)/);
            if (!m) {
              core.info('No related issue number found in PR body.');
              return;
            }
            const issueNumber = Number(m[1]);
            core.info(`Found related issue #${issueNumber}.`);

            // 2) 讀取該 issue 是否有 urgent 標籤
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            const hasUrgent = (issue.labels || []).some(l => (l.name || '').toLowerCase() === 'urgent');
            core.info(`Related issue urgent? ${hasUrgent}`);

            // 3) 若是 urgent，替本 PR 加上 urgent 標籤
            if (hasUrgent) {
              const prNumber = context.payload.pull_request.number;
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['urgent']
              });
              core.info(`Added 'urgent' label to PR #${prNumber}.`);
            } else {
              core.info('No urgent label added to PR.');
            }
