name: Sync urgent label from issue to PR 

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  sync-label:
    runs-on: ubuntu-latest
    steps:
      - name: Sync urgent label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail

          echo "== Read PR body =="
          PR_BODY="$(gh pr view "$PR_NUMBER" --repo "$REPO" --json body --jq '.body // ""')"

          echo "== Extract first #<number> from PR body =="
          ISSUE_NUMBER=$(printf '%s' "$PR_BODY" | grep -oE '#[0-9]+' | head -n1 | tr -d '#' || true)

          if [ -z "$ISSUE_NUMBER" ]; then
            echo "No related issue number found."
            exit 0
          fi
          echo "Found related issue #$ISSUE_NUMBER"

          echo "== Check if issue has urgent label =="
          ISSUE_LABELS=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json labels --jq '.labels[].name' || true)
          if printf '%s\n' "$ISSUE_LABELS" | grep -qi '^urgent$'; then
            echo "Issue has urgent label. Adding to PR..."
            gh pr edit "$PR_NUMBER" --repo "$REPO" --add-label urgent
          else
            echo "Issue does not have urgent label. Nothing to do."
          fi
