name: Sync urgent label from issue to PR

on:
  pull_request:
    types: [opened]

jobs:
  sync-label:
    runs-on: ubuntu-latest
    steps:
      - name: Extract related issue number
        id: extract_issue
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || '';
            const match = body.match(/#(\d+)/);
            core.setOutput('issue_number', match ? match[1] : '');

      - name: Check if issue has urgent label
        id: check_label
        if: steps.extract_issue.outputs.issue_number != ''
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = process.env.ISSUE_NUMBER;
            if (!issueNumber) {
              core.setOutput('has_urgent', false);
              return;
            }
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            core.setOutput('has_urgent', issue.data.labels.some(label => label.name === 'urgent'));
        env:
          ISSUE_NUMBER: ${{ steps.extract_issue.outputs.issue_number }}

      - name: Add urgent label to PR
        if: steps.check_label.outputs.has_urgent == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: urgent
