name: Sync urgent label from issue to PR

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  sync-label:
    runs-on: ubuntu-latest
    steps:
      # 1. 從 PR body 抓 issue number
      - name: Extract related issue number
        id: extract_issue
        run: |
          body="${{ github.event.pull_request.body }}"
          if [[ "$body" =~ \#([0-9]+) ]]; then
            echo "issue_number=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          else
            echo "issue_number=" >> "$GITHUB_OUTPUT"
          fi

      # 2. 檢查 issue 是否有 urgent 標籤
      - name: Check if issue has urgent label
        id: check_label
        if: ${{ steps.extract_issue.outputs.issue_number != '' }}
        uses: actions/github-script@v7
        env:
          ISSUE_NUMBER: ${{ steps.extract_issue.outputs.issue_number }}
        with:
          script: |
            const issueNumber = process.env.ISSUE_NUMBER;
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(issueNumber)
            });
            const hasUrgent = issue.labels.some(l => (l.name || '').toLowerCase() === 'urgent');
            core.setOutput('has_urgent', String(hasUrgent));

      # 3. 若需要，給 PR 加 urgent 標籤
      - name: Add urgent label to PR
        if: ${{ steps.check_label.outputs.has_urgent == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: urgent
