name: Notify if no reviewer assigned

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions:
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify if no reviewer assigned
        id: notify
        uses: kreuz123/notify-no-reviewer-action@main
        with:
          notify-target: @kimihuangoo-hash
          comment-template: |
               this PR is ready for review but currently has no reviewer. Please assign one.


      - run: |
          echo "has-reviewers=${{ steps.notify.outputs.has-reviewers }}"
          echo "notified=${{ steps.notify.outputs.notified }}"
