name: Notify if no reviewer assigned

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions:
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify if no reviewer assigned
        uses: kreuz123/notify-no-reviewer-action@main
        with:
          notify-target: my-org/backend-team
          # comment-template: |
          #   {notifyTarget}, this PR is ready for review but currently has no reviewer. Please assign one.
          # pr-number: ${{ github.event.pull_request.number }}
