name: Test Notify Unresolved Action

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  test-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Test notify-unresolved-threads-action
        uses: kreuz123/notify-unresolved-threads-action@main
        id: notify
        with:
          wait-seconds: 30
