name: Notify if no reviewer assigned

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions:
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify if no reviewer assigned
        uses: kreuz123/notify-no-reviewer-action@main
        with:
          notify-target: kimihuangoo-hash
          comment-template: |
             {notifyTarget}, please assign one.
          # pr-number: ${{ github.event.pull_request.number }}

      - run: |
          echo "has-reviewers=${{ steps.notify.outputs.has-reviewers }}"
          echo "notified=${{ steps.notify.outputs.notified }}"
